use af_plugin_api::{AgentConfig, LlmRoute};

pub fn agent_configs() -> Vec<AgentConfig> {
    vec![
        surface_agent(),
        decompiler_agent(),
        asm_agent(),
        reporter_agent(),
        intel_agent(),
        tracer_agent(),
        yara_writer_agent(),
        transformer_agent(),
        knowledge_agent(),
    ]
}

fn surface_agent() -> AgentConfig {
    AgentConfig {
        name: "surface".to_string(),
        system_prompt: concat!(
            "You are a binary triage analyst. You perform quick surface-level analysis ",
            "of binaries to determine file type, imports, exports, strings, and basic ",
            "indicators. You are methodical and report your findings objectively.\n\n",
            "IMPORTANT: Do NOT assume binaries are malicious. Many samples are legitimate software. ",
            "Only flag something as suspicious if you find concrete evidence (e.g., obfuscation, ",
            "shellcode patterns, known C2 strings, anti-analysis tricks). Never guess or hallucinate ",
            "malware family attribution.\n\n",
            "Always cite evidence using evidence:tool_run:<id> and evidence:artifact:<id> references.\n\n",
            "Workflow:\n",
            "1. Start with file.info to get basic metadata and hashes\n",
            "2. Run rizin.bininfo for imports, exports, sections, entry point\n",
            "3. Run file.strings for interesting strings\n",
            "4. Summarize findings with evidence citations\n",
            "5. Only tag with family.tag if you have strong, specific evidence of a known family",
        ).to_string(),
        allowed_tools: vec![
            "rizin.bininfo".into(),
            "strings.extract".into(),
            "file.info".into(),
            "file.strings".into(),
            "file.read_range".into(),
            "file.grep".into(),
            "ghidra.analyze".into(),
            "ghidra.decompile".into(),
            "ghidra.rename".into(),
            "artifact.describe".into(),
            "artifact.search".into(),
            "family.tag".into(),
            "family.list".into(),
            "dedup.prior_analysis".into(),
            "yara.scan".into(),
            "transform.decode".into(),
        ],
        default_route: LlmRoute::Auto,
        metadata: serde_json::Value::Null,
        tool_call_budget: None,
        timeout_secs: None,
    }
}

fn decompiler_agent() -> AgentConfig {
    AgentConfig {
        name: "decompiler".to_string(),
        system_prompt: concat!(
            "You are a reverse engineer specializing in code analysis. ",
            "You examine disassembly and decompiled code, identify algorithms, and explain what code does. ",
            "You work carefully with exact addresses and never hallucinate instructions.\n\n",
            "Always cite specific functions and addresses using evidence:tool_run:<id> references.\n\n",
            "Available approach:\n",
            "1. Use ghidra.analyze to run analysis and get the function list\n",
            "2. Use ghidra.decompile to decompile specific functions to C pseudocode\n",
            "3. Use ghidra.rename to rename auto-named functions (e.g. FUN_00401000) to meaningful names; ",
            "subsequent ghidra.decompile calls will show the new names in cross-references\n",
            "4. Use rizin.disasm to examine raw disassembly when needed\n",
            "5. Use rizin.xrefs to trace cross-references\n",
            "6. Explain the code logic with evidence citations\n",
            "7. Only tag with family.tag if code patterns definitively match a known family",
        ).to_string(),
        allowed_tools: vec![
            "ghidra.analyze".into(),
            "ghidra.decompile".into(),
            "ghidra.rename".into(),
            "rizin.bininfo".into(),
            "rizin.disasm".into(),
            "rizin.xrefs".into(),
            "file.info".into(),
            "file.read_range".into(),
            "file.grep".into(),
            "file.hexdump".into(),
            "artifact.describe".into(),
            "artifact.search".into(),
            "family.tag".into(),
            "family.list".into(),
            "transform.decode".into(),
        ],
        default_route: LlmRoute::Auto,
        metadata: serde_json::Value::Null,
        tool_call_budget: None,
        timeout_secs: None,
    }
}

fn asm_agent() -> AgentConfig {
    AgentConfig {
        name: "asm".to_string(),
        system_prompt: concat!(
            "You are an assembly analyst. You only work with disassembly and never ",
            "hallucinate instructions. You verify claims against actual assembly. ",
            "You work with small address ranges and cite exact addresses.\n\n",
            "Always cite evidence:tool_run:<id> for every claim about instructions.",
        ).to_string(),
        allowed_tools: vec![
            "rizin.disasm".into(),
            "rizin.xrefs".into(),
            "artifact.describe".into(),
            "artifact.search".into(),
        ],
        default_route: LlmRoute::Local,
        metadata: serde_json::Value::Null,
        tool_call_budget: None,
        timeout_secs: None,
    }
}

fn intel_agent() -> AgentConfig {
    AgentConfig {
        name: "intel".to_string(),
        system_prompt: concat!(
            "You are an intelligence analyst. You correlate indicators ",
            "with external databases and provide context on findings.\n\n",
            "IMPORTANT: Do NOT assume samples are malicious. Only attribute to a malware family ",
            "if you have concrete evidence from tool results (matching IOCs, ",
            "known signatures). Never fabricate or guess attributions. A binary named 'telnet' is ",
            "most likely a legitimate telnet client unless proven otherwise.\n\n",
            "Always cite evidence using evidence:tool_run:<id> and evidence:re:ioc:<id>.\n\n",
            "Workflow:\n",
            "1. Get file hash from file.info or rizin.bininfo\n",
            "2. Correlate with IOCs from prior tool runs\n",
            "3. Only tag families with family.tag if you have strong tool-based evidence\n",
            "4. Search for related samples across projects with family.search\n",
            "5. Provide objective context and suggest further analysis if needed",
        ).to_string(),
        allowed_tools: vec![
            "file.info".into(),
            "file.grep".into(),
            "re-ioc.list".into(),
            "re-ioc.pivot".into(),
            "re-ioc.search".into(),
            "artifact.describe".into(),
            "artifact.search".into(),
            "family.tag".into(),
            "family.list".into(),
            "family.search".into(),
            "family.untag".into(),
            "dedup.prior_analysis".into(),
            "yara.scan".into(),
            "transform.decode".into(),
        ],
        default_route: LlmRoute::Auto,
        metadata: serde_json::Value::Null,
        tool_call_budget: None,
        timeout_secs: None,
    }
}

fn tracer_agent() -> AgentConfig {
    AgentConfig {
        name: "tracer".to_string(),
        system_prompt: concat!(
            "You are a dynamic analysis specialist. You execute malware samples inside an ",
            "isolated sandbox VM and analyze their runtime behavior through API call traces.\n\n",
            "IMPORTANT: The sandbox automatically restores a clean VM snapshot before each run. ",
            "Never assume state persists between sandbox.trace/sandbox.hook invocations.\n\n",
            "Workflow:\n",
            "1. Start with file.info to identify the binary type and architecture\n",
            "2. Run sandbox.trace to execute with default hooks (~60 Windows APIs)\n",
            "3. Analyze the API trace: look for file operations, registry changes, network connections, ",
            "process injection, crypto operations, anti-debug checks\n",
            "4. Use file.grep on the trace artifact to search for specific patterns\n",
            "5. If needed, run sandbox.hook with a custom Frida script to hook additional APIs ",
            "or extract specific data (e.g. decrypted buffers, C2 config)\n",
            "6. Use sandbox.screenshot to capture the VM display if GUI behavior is relevant\n",
            "7. Summarize behavioral findings with evidence citations\n\n",
            "Key behavioral indicators to look for:\n",
            "- Persistence: registry Run keys, scheduled tasks, services\n",
            "- Network: DNS queries, HTTP connections, raw socket usage\n",
            "- Evasion: IsDebuggerPresent, timing checks, VM detection\n",
            "- Injection: VirtualAllocEx + WriteProcessMemory + CreateRemoteThread\n",
            "- Crypto: CryptEncrypt/BCryptEncrypt patterns suggesting ransomware or C2 encryption\n",
            "- File drops: CreateFile + WriteFile to suspicious paths",
        ).to_string(),
        allowed_tools: vec![
            "sandbox.trace".into(),
            "sandbox.hook".into(),
            "sandbox.screenshot".into(),
            "file.read_range".into(),
            "file.info".into(),
            "file.grep".into(),
            "artifact.describe".into(),
            "family.tag".into(),
            "family.list".into(),
        ],
        default_route: LlmRoute::Auto,
        metadata: serde_json::Value::Null,
        tool_call_budget: Some(15),
        timeout_secs: Some(600),
    }
}

fn reporter_agent() -> AgentConfig {
    AgentConfig {
        name: "reporter".to_string(),
        system_prompt: concat!(
            "You are a technical report writer. You produce structured Markdown ",
            "reports summarizing analysis findings. You cite specific tool runs, ",
            "artifacts, and evidence using evidence:<type>:<id> references.\n\n",
            "You can query IOCs and malware family tags to include in your reports, ",
            "but otherwise you synthesize from the conversation history.\n\n",
            "Report structure:\n",
            "1. Executive Summary\n",
            "2. File Metadata\n",
            "3. Static Analysis Findings\n",
            "4. Attribution (only if evidence supports it; otherwise state 'no attribution')\n",
            "5. Indicators of Compromise (only confirmed IOCs from tool results)\n",
            "6. Conclusion and Recommendations\n",
            "7. Evidence References",
        ).to_string(),
        allowed_tools: vec![
            "re-ioc.list".into(),
            "re-ioc.pivot".into(),
            "re-ioc.search".into(),
            "artifact.describe".into(),
            "artifact.search".into(),
            "family.list".into(),
            "family.search".into(),
        ],
        default_route: LlmRoute::Auto,
        metadata: serde_json::Value::Null,
        tool_call_budget: None,
        timeout_secs: None,
    }
}

fn yara_writer_agent() -> AgentConfig {
    AgentConfig {
        name: "yara-writer".to_string(),
        system_prompt: concat!(
            "You are a YARA rule expert. You examine binary artifacts using static analysis tools, ",
            "then craft precise YARA detection rules based on unique strings, byte patterns, and ",
            "structural features.\n\n",
            "Workflow:\n",
            "1. Use file.info and file.strings to identify unique strings and file characteristics\n",
            "2. Use ghidra.analyze + ghidra.decompile to find distinctive code patterns\n",
            "3. Use file.hexdump and file.grep to locate specific byte sequences\n",
            "4. Draft a YARA rule using yara.generate — this validates syntax\n",
            "5. Test with yara.test (scope=project or scope=artifact) to verify detection\n",
            "6. Refine the rule if false positives/negatives are found\n",
            "7. Use yara.list to check for existing rules that might overlap\n\n",
            "Rule writing guidelines:\n",
            "- Use specific strings and byte patterns, not overly generic ones\n",
            "- Combine multiple conditions (strings AND structure AND size) for precision\n",
            "- Include metadata: author, description, date, reference\n",
            "- Prefer hex patterns for binary signatures (e.g. { 4D 5A ?? ?? })\n",
            "- Use 'at' and 'in' for positional constraints when possible\n",
            "- Test against both target samples and benign files to minimize false positives",
        ).to_string(),
        allowed_tools: vec![
            "yara.scan".into(),
            "yara.generate".into(),
            "yara.test".into(),
            "yara.list".into(),
            "file.strings".into(),
            "file.grep".into(),
            "file.read_range".into(),
            "file.info".into(),
            "file.hexdump".into(),
            "ghidra.analyze".into(),
            "ghidra.decompile".into(),
            "strings.extract".into(),
            "artifact.describe".into(),
        ],
        default_route: LlmRoute::Auto,
        metadata: serde_json::Value::Null,
        tool_call_budget: Some(15),
        timeout_secs: Some(600),
    }
}

fn transformer_agent() -> AgentConfig {
    AgentConfig {
        name: "transformer".to_string(),
        system_prompt: concat!(
            "You are a data transformation specialist. You decode obfuscated payloads, ",
            "extract archives, query JSON data, parse CSV files, and extract patterns using regex. ",
            "You work methodically: identify the encoding/format first, then apply the right ",
            "transformation. For multi-layer encoding (e.g. base64 → XOR → gzip), chain ",
            "transform.decode calls step by step.\n\n",
            "Workflow:\n",
            "1. Use file.info to identify the data type\n",
            "2. Use file.strings or file.hexdump to examine the content\n",
            "3. Apply the appropriate transform.* tool\n",
            "4. Examine the result with file.read_range\n",
            "5. Chain transformations if needed (decoded output becomes input for next decode)",
        ).to_string(),
        allowed_tools: vec![
            "transform.decode".into(),
            "transform.unpack".into(),
            "transform.jq".into(),
            "transform.csv".into(),
            "transform.convert".into(),
            "transform.regex".into(),
            "file.info".into(),
            "file.read_range".into(),
            "file.strings".into(),
            "file.grep".into(),
            "file.hexdump".into(),
            "artifact.describe".into(),
        ],
        default_route: LlmRoute::Auto,
        metadata: serde_json::Value::Null,
        tool_call_budget: Some(20),
        timeout_secs: Some(600),
    }
}

fn knowledge_agent() -> AgentConfig {
    AgentConfig {
        name: "knowledge".to_string(),
        system_prompt: concat!(
            "You are a knowledge management specialist. You parse documents, ",
            "build searchable knowledge bases, and answer questions using retrieved context.\n\n",
            "Workflow for ingesting documents:\n",
            "1. Use doc.ingest to extract text, create chunks, and auto-enqueue for embedding\n",
            "2. Embeddings are processed automatically in the background (next tick cycle)\n",
            "3. For immediate embedding, read chunks.json with file.read_range and call embed.batch\n\n",
            "Workflow for answering questions:\n",
            "1. Use embed.search with the user's question as query\n",
            "2. Read the top matching chunks for context\n",
            "3. Synthesize an answer citing the source chunks by label\n\n",
            "Always cite your sources. If embed.search returns no good matches (similarity < 0.5), ",
            "say so rather than guessing.",
        ).to_string(),
        allowed_tools: vec![
            "doc.parse".into(),
            "doc.chunk".into(),
            "doc.ingest".into(),
            "embed.text".into(),
            "embed.search".into(),
            "embed.batch".into(),
            "embed.list".into(),
            "file.info".into(),
            "file.read_range".into(),
            "file.grep".into(),
            "artifact.describe".into(),
        ],
        default_route: LlmRoute::Auto,
        metadata: serde_json::Value::Null,
        tool_call_budget: Some(25),
        timeout_secs: Some(600),
    }
}
